### PR TITLE
Fix photo loss

### PR DESCRIPTION
**Pull request by pvalsecc**

### CODE REVIEW

**Comment by asaunier** [comment]
@pvalsecc @gberaudo Why opening and closing this PR in a row?

**Comment by pvalsecc** [comment]
Because I've opened it against the wrong fork.

**Comment by asaunier** [comment]
Isn't it interesting for c2corg as well?

**Comment by pvalsecc** [comment]
Not so easy... c2corg will then need a script run monthly that deletes the photos that are not referenced anymore.
Or not. We leak the resizes anyway...
Anyway, we'll need to merge back all the modifs one day, like we did in the past.

**Comment by pvalsecc** [comment]
For reference, the PR in the fork: https://github.com/camptocamp/saccas_photo_backend/pull/145

**Pull request closed without merging**
