### PR TITLE
Handle duplicates in migration script

### PR DESCRIPTION
**Pull request by arnaud-morvan**

### CODE REVIEW

**Comment by asaunier** [comment]
Is this PR related to https://github.com/c2corg/v6_api/issues/363 ?

**Comment by arnaud-morvan** [comment]
Not really related to c2corg/v6_api#363
Here I use the archive table to get all images (including history, old versions) but there is duplicates on filename, and this cause errors as there is multiple thread processing the same image in parallel.

**Comment by arnaud-morvan** [comment]
I need all distinct filenames, with a key for batch fixed order in batch requests with offset and limit.

**Comment by asaunier** [comment]
> there is duplicates on filename

That's what I meant when mentioning c2corg/v6_api#363

The PR seems OK to me. The temp table is added to the copy of v5 database used for the migration, right?

Perhaps it's not really needed though because the association has created a tool to handle the filename duplicates in the v5 database. It's not automatic though, the association will have to figure out if there are duplicates left just before the migration and treat them.

But I guess you need the current change in order to automatically import the v5 database every day even though duplicates are remaining anyway, correct?

**Comment by arnaud-morvan** [comment]
Yes, I need it now for the migration.
Note that it seems normal to have filename duplicates between versions of the same image. Nothing to do with duplicated filenames between different current images. So this is not directly related to c2corg/v6_api#363.

**Comment by asaunier** [comment]
> Note that it seems normal to have filename duplicates between versions of the same image.

Indeed. If changes are done on the image metadata but not on the file itself, archives of the same document id will have the same filename attribute.

**Pull request merged**
